# Deploy to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Generate version file
      run: |
        # Create a simple version.json file based on commit info
        echo "{\"version\": \"v$(date +%s)\", \"commit\": \"$GITHUB_SHA\", \"updated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > version.json
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,node_modules,server.js,package*.json,update-version.js'
